name: Build with Watcom wasm and wlink
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: open-watcom/setup-watcom@v1
      with:
        version: "2.0"
        target:  "dos"
    - run: |
        wmake -h -u -f Makefile.wat
        make -f Makefile.wat clean
        make -f Makefile.wat

name: UploadRelease
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Release
        uses: softprops/action-gh-release@v3

            
