name: Build with Watcom wasm and wlink
on: [push]
jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: open-watcom/setup-watcom@v1
      with:
        version: "2.0"
        target:  "dos"
    - run: |
        make
    - uses: joncloud/dos-build-action@v1
      with:
        run: |
          C:
          CD TASM
          MAKE CLEAN
          MAKE
        programs: |
          tasm/TASM.EXE:C:\TASM.EXE
        conf: |
          [dosbox]
          memsize=256

          [cpu]
          cycles=max
          turbo=true
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          3c509.com
          *.map
          *.lst
          tasm/*.COM
          tasm/*.MAP
          tasm/*.LST
            
